DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS room;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  balance INTEGER NOT NULL
);

CREATE TABLE room (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  room TEXT NOT NULL,
  temp_password TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);
